export const SUPPORTED_LANGUAGES: { code: string; name: string; nativeName: string }[] = [
  { code: "en", name: "English", nativeName: "English" },
  { code: "es", name: "Spanish", nativeName: "Español" },
  { code: "ar", name: "Arabic", nativeName: "العربية" },
  { code: "fr", name: "French", nativeName: "Français" },
  { code: "so", name: "Somali", nativeName: "Soomaali" },
  { code: "sw", name: "Swahili", nativeName: "Kiswahili" },
  { code: "am", name: "Amharic", nativeName: "አማርኛ" },
  { code: "ti", name: "Tigrinya", nativeName: "ትግርኛ" },
  { code: "fa", name: "Farsi / Persian", nativeName: "فارسی" },
  { code: "ps", name: "Pashto", nativeName: "پښتو" },
  { code: "ur", name: "Urdu", nativeName: "اردو" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা" },
  { code: "ne", name: "Nepali", nativeName: "नेपाली" },
  { code: "my", name: "Burmese", nativeName: "မြန်မာဘာသာ" },
  { code: "vi", name: "Vietnamese", nativeName: "Tiếng Việt" },
  { code: "zh", name: "Chinese (Simplified)", nativeName: "中文（简体）" },
  { code: "ht", name: "Haitian Creole", nativeName: "Kreyòl ayisyen" },
  { code: "pt", name: "Portuguese", nativeName: "Português" },
  { code: "ru", name: "Russian", nativeName: "Русский" },
  { code: "uk", name: "Ukrainian", nativeName: "Українська" },
  { code: "ku", name: "Kurdish (Kurmanji)", nativeName: "Kurdî" },
  { code: "tr", name: "Turkish", nativeName: "Türkçe" },
  { code: "tl", name: "Tagalog / Filipino", nativeName: "Tagalog" },
  { code: "ha", name: "Hausa", nativeName: "Hausa" },
  { code: "om", name: "Oromo", nativeName: "Afaan Oromoo" },
  { code: "si", name: "Sinhala", nativeName: "සිංහල" },
];
